/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkStockholmExergiDesignToEngineeringRouteImport } from './routes/work/stockholm-exergi-design-to-engineering'
import { Route as WorkStexuiRouteImport } from './routes/work/stexui'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkStockholmExergiDesignToEngineeringRoute =
  WorkStockholmExergiDesignToEngineeringRouteImport.update({
    id: '/work/stockholm-exergi-design-to-engineering',
    path: '/work/stockholm-exergi-design-to-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkStexuiRoute = WorkStexuiRouteImport.update({
  id: '/work/stexui',
  path: '/work/stexui',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/stexui': typeof WorkStexuiRoute
  '/work/stockholm-exergi-design-to-engineering': typeof WorkStockholmExergiDesignToEngineeringRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/stexui': typeof WorkStexuiRoute
  '/work/stockholm-exergi-design-to-engineering': typeof WorkStockholmExergiDesignToEngineeringRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/work/stexui': typeof WorkStexuiRoute
  '/work/stockholm-exergi-design-to-engineering': typeof WorkStockholmExergiDesignToEngineeringRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/work/stexui'
    | '/work/stockholm-exergi-design-to-engineering'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/work/stexui'
    | '/work/stockholm-exergi-design-to-engineering'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/work/stexui'
    | '/work/stockholm-exergi-design-to-engineering'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  WorkStexuiRoute: typeof WorkStexuiRoute
  WorkStockholmExergiDesignToEngineeringRoute: typeof WorkStockholmExergiDesignToEngineeringRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/stockholm-exergi-design-to-engineering': {
      id: '/work/stockholm-exergi-design-to-engineering'
      path: '/work/stockholm-exergi-design-to-engineering'
      fullPath: '/work/stockholm-exergi-design-to-engineering'
      preLoaderRoute: typeof WorkStockholmExergiDesignToEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/stexui': {
      id: '/work/stexui'
      path: '/work/stexui'
      fullPath: '/work/stexui'
      preLoaderRoute: typeof WorkStexuiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  WorkStexuiRoute: WorkStexuiRoute,
  WorkStockholmExergiDesignToEngineeringRoute:
    WorkStockholmExergiDesignToEngineeringRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
