/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkPersonalIndexRouteImport } from './routes/work/personal/index'
import { Route as WorkClientIndexRouteImport } from './routes/work/client/index'
import { Route as WorkPersonalJosuiRouteImport } from './routes/work/personal/josui'
import { Route as WorkClientDesignToEngineeringAtStockholmExergiRouteImport } from './routes/work/client/design-to-engineering-at-stockholm-exergi'
import { Route as WorkClientContractFirstApisAtStockholmExergiRouteImport } from './routes/work/client/contract-first-apis-at-stockholm-exergi'

const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPersonalIndexRoute = WorkPersonalIndexRouteImport.update({
  id: '/work/personal/',
  path: '/work/personal/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkClientIndexRoute = WorkClientIndexRouteImport.update({
  id: '/work/client/',
  path: '/work/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPersonalJosuiRoute = WorkPersonalJosuiRouteImport.update({
  id: '/work/personal/josui',
  path: '/work/personal/josui',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkClientDesignToEngineeringAtStockholmExergiRoute =
  WorkClientDesignToEngineeringAtStockholmExergiRouteImport.update({
    id: '/work/client/design-to-engineering-at-stockholm-exergi',
    path: '/work/client/design-to-engineering-at-stockholm-exergi',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkClientContractFirstApisAtStockholmExergiRoute =
  WorkClientContractFirstApisAtStockholmExergiRouteImport.update({
    id: '/work/client/contract-first-apis-at-stockholm-exergi',
    path: '/work/client/contract-first-apis-at-stockholm-exergi',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/readme': typeof ReadmeRoute
  '/work/': typeof WorkIndexRoute
  '/work/client/contract-first-apis-at-stockholm-exergi': typeof WorkClientContractFirstApisAtStockholmExergiRoute
  '/work/client/design-to-engineering-at-stockholm-exergi': typeof WorkClientDesignToEngineeringAtStockholmExergiRoute
  '/work/personal/josui': typeof WorkPersonalJosuiRoute
  '/work/client/': typeof WorkClientIndexRoute
  '/work/personal/': typeof WorkPersonalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/readme': typeof ReadmeRoute
  '/work': typeof WorkIndexRoute
  '/work/client/contract-first-apis-at-stockholm-exergi': typeof WorkClientContractFirstApisAtStockholmExergiRoute
  '/work/client/design-to-engineering-at-stockholm-exergi': typeof WorkClientDesignToEngineeringAtStockholmExergiRoute
  '/work/personal/josui': typeof WorkPersonalJosuiRoute
  '/work/client': typeof WorkClientIndexRoute
  '/work/personal': typeof WorkPersonalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/readme': typeof ReadmeRoute
  '/work/': typeof WorkIndexRoute
  '/work/client/contract-first-apis-at-stockholm-exergi': typeof WorkClientContractFirstApisAtStockholmExergiRoute
  '/work/client/design-to-engineering-at-stockholm-exergi': typeof WorkClientDesignToEngineeringAtStockholmExergiRoute
  '/work/personal/josui': typeof WorkPersonalJosuiRoute
  '/work/client/': typeof WorkClientIndexRoute
  '/work/personal/': typeof WorkPersonalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/readme'
    | '/work/'
    | '/work/client/contract-first-apis-at-stockholm-exergi'
    | '/work/client/design-to-engineering-at-stockholm-exergi'
    | '/work/personal/josui'
    | '/work/client/'
    | '/work/personal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/readme'
    | '/work'
    | '/work/client/contract-first-apis-at-stockholm-exergi'
    | '/work/client/design-to-engineering-at-stockholm-exergi'
    | '/work/personal/josui'
    | '/work/client'
    | '/work/personal'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/readme'
    | '/work/'
    | '/work/client/contract-first-apis-at-stockholm-exergi'
    | '/work/client/design-to-engineering-at-stockholm-exergi'
    | '/work/personal/josui'
    | '/work/client/'
    | '/work/personal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  ReadmeRoute: typeof ReadmeRoute
  WorkIndexRoute: typeof WorkIndexRoute
  WorkClientContractFirstApisAtStockholmExergiRoute: typeof WorkClientContractFirstApisAtStockholmExergiRoute
  WorkClientDesignToEngineeringAtStockholmExergiRoute: typeof WorkClientDesignToEngineeringAtStockholmExergiRoute
  WorkPersonalJosuiRoute: typeof WorkPersonalJosuiRoute
  WorkClientIndexRoute: typeof WorkClientIndexRoute
  WorkPersonalIndexRoute: typeof WorkPersonalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/personal/': {
      id: '/work/personal/'
      path: '/work/personal'
      fullPath: '/work/personal/'
      preLoaderRoute: typeof WorkPersonalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/client/': {
      id: '/work/client/'
      path: '/work/client'
      fullPath: '/work/client/'
      preLoaderRoute: typeof WorkClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/personal/josui': {
      id: '/work/personal/josui'
      path: '/work/personal/josui'
      fullPath: '/work/personal/josui'
      preLoaderRoute: typeof WorkPersonalJosuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/client/design-to-engineering-at-stockholm-exergi': {
      id: '/work/client/design-to-engineering-at-stockholm-exergi'
      path: '/work/client/design-to-engineering-at-stockholm-exergi'
      fullPath: '/work/client/design-to-engineering-at-stockholm-exergi'
      preLoaderRoute: typeof WorkClientDesignToEngineeringAtStockholmExergiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/client/contract-first-apis-at-stockholm-exergi': {
      id: '/work/client/contract-first-apis-at-stockholm-exergi'
      path: '/work/client/contract-first-apis-at-stockholm-exergi'
      fullPath: '/work/client/contract-first-apis-at-stockholm-exergi'
      preLoaderRoute: typeof WorkClientContractFirstApisAtStockholmExergiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  ReadmeRoute: ReadmeRoute,
  WorkIndexRoute: WorkIndexRoute,
  WorkClientContractFirstApisAtStockholmExergiRoute:
    WorkClientContractFirstApisAtStockholmExergiRoute,
  WorkClientDesignToEngineeringAtStockholmExergiRoute:
    WorkClientDesignToEngineeringAtStockholmExergiRoute,
  WorkPersonalJosuiRoute: WorkPersonalJosuiRoute,
  WorkClientIndexRoute: WorkClientIndexRoute,
  WorkPersonalIndexRoute: WorkPersonalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
